version: '3'

services:
  tests:
    image: ugc-image
    volumes:
      - .:/ugc/tests
#    entrypoint: >
#      sh -c "python3 -m pytest -s /ugc/tests"
    depends_on:
      - kafka
      - ugc_api
    env_file: ./envs/.env
