version: '3'

services:
  # Kafka
  zookeeper-kafka:
    image: wurstmeister/zookeeper
    container_name: zookeeper-kafka
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9093:9093"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-kafka:2181'
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "view_progress"
    depends_on:
      - zookeeper-kafka

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper-kafka:2181"

# Clickhouse
  zookeeper-click:
    image: zookeeper:3.5
    container_name: zookeeper-click
    hostname: zookeeper-click

  clickhouse-node1:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/data/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper-click

  clickhouse-node2:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./clickhouse/data/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper-click

  clickhouse-node3:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./clickhouse/data/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper-click

  clickhouse-node4:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./clickhouse/data/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper-click

  ugc_api:
    build: ugc
    container_name: ugc_api
    image: ugc-image
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    env_file:
     - envs/.env
    volumes:
      - ./ugc:/ugc
    expose:
      - 8000

  ugc_api_2:
    build: ugc_2
    container_name: ugc_api_2
    ports:
      - "8090:8090"
    depends_on:
      - mongodb
    env_file:
     - envs/.env
    volumes:
      - ./ugc_2:/ugc
    expose:
      - 8090

  ugc_etl:
    build: ugc_etl
    container_name: ugc_etl
    depends_on:
      - kafka
      - clickhouse-node1
      - clickhouse-node2
      - clickhouse-node3
      - clickhouse-node4
    restart: on-failure
    env_file:
     - envs/.env

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - ugc_api
    ports:
      - "80:80"


