version: "3"
services:
  redpanda:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:v2.1.1
    user: "1990:1990"
    restart: on-failure
    hostname: redpanda
    ports:
    - "8080:8080"
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9092"]
          schemaRegistry:
            enabled: false
    depends_on:
      - kafka

  kafka:
    restart: always
    hostname: kafka
    container_name: kafka
    image: 'quay.io/debezium/kafka:1.8'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_RETENTION_HOURS: 168
      KAFKA_LOG_CLEANUP_POLICY: "delete"
      KAFKA_LOCAL_RETENTION_MS: 60000
      ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper

  zookeeper:  # the configuration manager
    hostname: zookeeper
    container_name: zookeeper
    image: 'quay.io/debezium/zookeeper:1.8'
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped